### ISSUE TITLE
White matter and Grey matter Slice

### ISSUE THREAD

**Issue by femem** [sblowers/VaPor#1]
Can this code give a slice of white matter and grey matter in the brain from MRI Scans?. I tried to use planecut.m but it did not work. It only worked for a slice of temperature distribution in the brain.

**Comment by sblowers** [comment]
The internal variables for grey and white matter fractions are "GreyMatter" and "WhiteMatter" so the planecut function should work with planecut(Dir,Val,GreyMatter) or planecut(Dir,Val,WhiteMatter)
